# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    person_model:
      class: AppBundle\Model\PersonModel
      arguments:
          - '@service_container'
